DELETE  http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cGlyZSI6MTczNDI3MTQxOSwidXNlcklkIjoyfQ.u5iIaMWvkELcnjdi0co1BBGfGtaEWij8RQq_EZMBkes