DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cGlyZSI6MTczNDI3MDIyMCwidXNlcklkIjoyfQ.kHYBpYRfsSxU0aMS3DIUo5ZpSGg02VFU443dyOfY2bM